* HISTORY

** Version 1.0.8

   Camel Case seems to be mislabeled.
   https://github.com/akicho8/string-inflection/issues/25

   When it is simply =camelcase=, it means the name with the leading letters in lowercase.
   The name with the initial capital letter is called the =pascal-case=.

*** Behavior of the function has changed

    Before: camelcase --> FooBar
    After:  camelcase --> fooBar

*** Function name changed as well

    camelcase       --> pascal-case
    lower-camelcase --> camelcase

*** Add alias

    (fset 'string-inflection-upper-camelcase-function 'string-inflection-pascal-case-function)
    (fset 'string-inflection-lower-camelcase-function 'string-inflection-camelcase-function)

    (fset 'string-inflection-upper-camelcase-p 'string-inflection-pascal-case-p)
    (fset 'string-inflection-lower-camelcase-p 'string-inflection-camelcase-p)

*** Remove camelize function

    Originally we had defined functions of both =camelcase= and =camelize= names.
    I deleted the function containing =camelize= to make it simple.
