* HISTORY

** Version 1.1.0

   - Support non ascii [[https://github.com/akicho8/string-inflection/pull/39][#39]]
   - Use (bounds-of-thing-at-point) for word detection [[https://github.com/akicho8/string-inflection/pull/41][#41]]
   - Implement string-inflect-final-position [[https://github.com/akicho8/string-inflection/pull/43][#43]]

   =string-inflection-skip-backward-when-done= is deprecated.
   Use the =string-inflection-final-position= option instead.
   However, leaving it as the default seems to be the easiest to use.

** Version 1.0.16

   Fix [[https://github.com/akicho8/string-inflection/issues/34][#34]] kebabing a region can insert an unexpected hyphen

   add =string-inflection-erase-chars-when-region= variable

   Changed behavior when selecting region.

#+BEGIN_SRC
before: Foo::Bar --> foo_bar
after:  Foo::Bar --> foo::bar
#+END_SRC

   Include =:= in =string-inflection-erase-chars-when-region= if want to behave as before.

** Version 1.0.14

   Merged [[https://github.com/akicho8/string-inflection/pull/32][PR #32]] Use defcustom and Change Some Wording

** Version 1.0.13

   Fix [[https://github.com/akicho8/string-inflection/issues/31][#31]] Better Whitespace Handling When Converting a Region

** Version 1.0.12

   Fix [[https://github.com/akicho8/string-inflection/issues/30][#30]] string-inflection-underscore affects C++ method accessors

#+BEGIN_SRC
before: fooBar->method --> foo_bar_>method
after:  fooBar->method --> foo_bar->method
#+END_SRC

** Version 1.0.11

   Merged [[https://github.com/akicho8/string-inflection/pull/28][PR #28]] Make string-inflection-get-current-word work more sensibly when transient mark mode is off

** Version 1.0.10

   Merged [[https://github.com/akicho8/string-inflection/pull/26][PR #26]] Add `Capital_Underscore_Form`

   add string-inflection-capital-underscore function

   The behavior of =string-inflection-all-cycle= has changed

#+BEGIN_SRC
before: foo_bar => FOO_BAR => FooBar => fooBar => foo-bar => foo_bar
after:  foo_bar => FOO_BAR => FooBar => fooBar => foo-bar => Foo_Bar => foo_bar
#+END_SRC

** Version 1.0.9

   Bugfix [[https://github.com/akicho8/string-inflection/issues/27][issue #25]] When executing kebab-case etc., point advances to the next word, and the previous word can not be converted continuously

** Version 1.0.8

   [[https://github.com/akicho8/string-inflection/issues/25][issue #25]]

   When it is simply =camelcase=, it means the name with the leading letters in lowercase.

   The name with the initial capital letter is called the =pascal-case=.

*** Behavior of the camelcase function has changed

    | Before | After  |
    |--------+--------|
    | FooBar | fooBar |

*** Function name changed as well

    | Before          | After       |
    |-----------------+-------------|
    | camelcase       | pascal-case |
    | lower-camelcase | camelcase   |

*** Add alias

    #+BEGIN_SRC elisp
(fset 'string-inflection-upper-camelcase-function 'string-inflection-pascal-case-function)
(fset 'string-inflection-lower-camelcase-function 'string-inflection-camelcase-function)

(fset 'string-inflection-upper-camelcase-p 'string-inflection-pascal-case-p)
(fset 'string-inflection-lower-camelcase-p 'string-inflection-camelcase-p)
    #+END_SRC

*** Remove camelize function

    Originally we had defined functions of both =camelcase= and =camelize= names.

    I deleted the function containing =camelize= to make it simple.
